services:
  recipe-book-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: recipe-book-db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  recipe-book-api:
    build:
      context: ./api
      target: local
    # Running in local dev
    container_name: recipe-book-api
    restart: always
    environment:
      - PORT=4000
      - ENV=dev
      - SERVICE_NAME=recipe-book-api
    depends_on:
      recipe-book-db:
        condition: service_healthy
    expose:
      - "4000"
    ports:
        - "4000:4000"
    volumes:
       - "./api:/usr/src/app/"
       - "/usr/src/app/node_modules"
    links:
      - recipe-book-db

  recipe-book-ui:
    build:
      context: ./ui
    depends_on:
      - recipe-book-api
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://recipe-book-api:4000/graphql
    container_name: recipe-book-ui
    stdin_open: true
    volumes:
       - "./ui:/usr/src/app/"
       - "/usr/src/app/node_modules"

volumes:
  db:
    driver: local
