schema: "api/schema.graphql"
documents: "frontend/app/graphql/*.ts"
extensions:
  codegen:
    overwrite: true
    generates:
      ./frontend/app/graphql.type.tsx:
        plugins:
          - "typescript"
          - "typescript-operations"
      ./api/src/features/graphql.type.ts:
        plugins:
          - "typescript"
      ./ui/graphql.schema.json:
        plugins:
          - "introspection"
